### ISSUE TITLE
account_analytic_required - name conflict

### ISSUE THREAD

**Issue by yvaucher** [OCA/account-analytic#28]
This module name conflicts with 

https://github.com/Vauxoo/addons-vauxoo/blob/8.0/account_analytic_required/__openerp__.py

Which is registered on apps.odoo.com

@luistorresm is your module the same?

**Comment by nhomar** [comment]
Hello.

@yvaucher 

We made our internal review, and we realize that for some reason this module landed on addons-vauxoo for the time we copied and paste things there.

It is the same module, and we migrated to v8.0 already with 2 or 3 little modifications, I am wondered why it says coded by Luis, I just supose it was an error but we will fix it ASAP in order to ledft only one module on apps (the oca's ones) and the little modifications we did that differ from what the OCA's ones have we will make a proper PR,

THanks for point this out.

Regards.

**Comment by yvaucher** [comment]
@nhomar Great, thanks.

BTW there was few other modules in almost the same conditions:
https://github.com/OCA/department/issues/43
https://github.com/OCA/purchase-workflow/issues/122

(cc @dmo-odoo for apps.odoo.com)

**Comment by yvaucher** [comment]
@nhomar @luistorresm Just be aware there is another PR on module `account_analytic_required` from @luc-demeyer here https://github.com/OCA/account-analytic/pull/26

**Comment by nhomar** [comment]
@yvaucher

We will make this review in some days sorry for the delay we will try to accelerate the process just too busy.

**Comment by moylop260** [comment]
https://github.com/OCA/department/issues/43#issuecomment-113546731
